### ISSUE TITLE
Changing project title seems to have orphaned a shared project

### ISSUE THREAD

**Issue by zachsa** [teleporthq/teleport-documentation#78]
Hi - I'm not sure this is the best place to post this, I think I found a bug:

1. I created a project (Person A),
2. Shared the project with (Person B) to edit
3. Then I renamed my project
4. Now when Person B edits the project, his changes don't reflect on my original project
5. Person B has the project on a different URL than mine (mine is `/projects/presentation-page-ez24v9`, which doesn't reflect the project rename). Person B's project is at `/projects/somisana-7maj9n`, which does reflect the rename
6. After Person B invited me as an editor to that project, I can now see the changes.
7. However on my workspace page, there is nothing under 'shared with me'. Instead I still see my original project, which links to the old URL and doesn't include edits made on the new URL. 

But... it does look like the edits on the new URL are being indicated in the clickable project detail

![image](https://github.com/teleporthq/teleport-documentation/assets/6336500/86390530-2355-4b37-aabc-cd405913d499)

**Comment by paulbrie** [comment]
Hi! We're going to check and will come back to you.

**Comment by zachsa** [comment]
Thank you for such a quick response. Here are some links:

- My workspace: https://play.teleporthq.io/workspaces/my-workspace-g2ynhg
- That contains one project, that when clicked, opens to https://play.teleporthq.io/projects/presentation-page-ez24v9 (doesn't contain the latest edits, even though the blurb says the project was edited recently)
- However it SHOULD have opened to https://play.teleporthq.io/projects/somisana-7maj9n. But this project seems to belong to "Person B". Person B did actually invite me to edit it, and it worked. But then Person B, when he went to his workspace, was presented an option to add the anonymous project to his workspace - he clicked yes. That seems to have removed my edit access to this project. 

I think my request for edit access may not have triggered an email notification - Person B doesn't seem to have received it.

**Comment by anamariaoros** [comment]
Hi, @zachsa 

We investigated the issue you mentioned and, unfortunately, we didn't manage to reproduce it. 
We didn't find any problem on our end regarding real time collaboration but, we suspect that when you shared your project, your collaborator cloned it. 
If you have any other questions please ping me.

**Comment by zachsa** [comment]
Hi - the "Edited 6 minutes" ago as highlighted in yellow. Would that be the case for cloned projects? 

Also, Initially I was seeing his edits on the project - I actually tried to undo one of those edits by pressing "ctrl + z". could that have undone the share?

**Comment by anamariaoros** [comment]
Hi @zachsa 

It is true that when the user B clones a project, the project is added to the user B's workspace and the user A cannot see any changes to that cloned project. So basically, when you perform the cloning operation you end up with 2 different projects with 2 different owners.

Ctrl+z doesn't undo the share.

How did you add user B as a collaborator? What type of link did you send? Can you send me some STR?
Also, can you check with your collaborator that he works on the project that is in the "Shared with Me" section/tab?

If you have any issues regarding this issues, can you please ping us on Crisp ( you can find the Crisp icon on the bottom right corner in the platform ).

**Comment by zachsa** [comment]
Hi - there were problems in our workflow. Apologies! And thank you for a great website builder.
